---
name: Push docker image on Dockerhub
on:
  push:
  workflow_dispatch:

jobs:
  build-dockerhub:
    runs-on: ubuntu-latest

    environment:
      name: dockerhub
    steps:
      - name: build dockerfile for dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_IMAGE_DH }}:latest
